[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Christian Hagau", email = "hagau@ibr.cs.tu-bs.de"},
]
dependencies = [
    "matplotlib>=3.8.2",
    "numpy",
    "jsonpickle",
    "ujson",
    "pandas",
    "scipy>=1.8.1",
    "SQLAlchemy",
    "seaborn",
    "sphinx",
    "numpydoc",
    "sphinx-rtd-theme",
    "recommonmark",
    "tabulate",
    "bottleneck",
    "numexpr",
    "pyarrow",
    "dask[complete]==2023.8.1",
    "dask-jobqueue",
    "distributed==2023.8.1",
    "graphviz>=0.20.1",
    "ipython>=8.25.0",
    "ipdb>=0.13.13",
]
requires-python = ">=3.10,<3.13"
license = {text = "GPLv3"}
readme = "README.md"
[tool]
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[tool.pdm.dev-dependencies]
dev = [
    "pylint>=2.15.5",
    "autopep8",
    "wrapt",
    "typed-ast",
    "rope",
    "pycodestyle",
    "mccabe",
    "lazy-object-proxy",
    "isort",
    "mypy>=0.982",
    "autoflake>=1.7.7",
]
